### PR TITLE
Created Favicon

### LINKED ISSUE #1: [FEATURE] Create favicon
## Requirements
- When viewing the React Example app in my browser, I should be able to see the custom favicon image that you added in browser tab title.

### PR DESCRIPTION
**Pull request by x5401**
The website did not have a favicon, so this pull request creates a favicon for the website.

### CODE REVIEW

**Comment by DandyLyons** [comment]
https://github.com/DandyLyons/React-Example/issues/1

**Comment by DandyLyons** [comment]
Fantastic job you two! 🥳

One small change: Please remove this commented line from `index.html`: 
Screenshot 2023-11-03 at 1 53 16 PM

Normally for a change this small, I would probably just make the change myself, but I want to give you some practice with revisions. 

Screenshot 2023-11-03 at 1 59 55 PM


Simply make the change, commit it, and push it to the same upstream. (A regular `git push` should be enough). Then the commit should show up in this PR. (No need to make a new PR). After that I'll merge. 👍🏼

**Comment by Amandaan** [comment]
Hi Daniel, I don't see a Request Review button. Are you able to merge?

**Comment by DandyLyons** [comment]
Oh I see! It looks like you didn't have the request review button because I had to do a review first. That's my fault not yours. Anyways, that's why it's good to practice. 

For the future, here's info about requesting a review: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review

I'll go ahead and merge it now. 👍🏼

**Review by DandyLyons — COMMENTED** [review]
Great job!

**Pull request merged**
